### ISSUE TITLE
Navpatch seems to not work anymore

### ISSUE THREAD

**Issue by plrusek** [DeckThemes/SDH-CssLoader#110]
Beta branch of SteamOS (3.5.7), prerelease of Decky Loader (v2.10.15-pre2). Turning on Navpatch doesn't do anything. Themes hiding UI elements still let you select hidden elements. Going back into the menu at any point will have the Navpatch option turned off. Seems to be a relatively recent issue.

**Comment by suchmememanyskill** [comment]
Yeah, found it earlier today too. Thanks for making an issue for this

**Comment by suchmememanyskill** [comment]
(resolved a while ago)
